### ISSUE TITLE
Invoking rooibosC does nothing

### ISSUE THREAD

**Issue by blockscoped** [georgejecook/rooibosPreprocessor#1]
I've installed `rooibos-preprocessor` locally and invoked it like so:
```
npx rooibosC <path/to/test/specs> <path/to/root/dir>
```
This currently does nothing.
It seems the `commander` setup is incorrect.

**Comment by georgejecook** [comment]
never saw this: I don't invoke it with npx

**Comment by blockscoped** [comment]
Maybe it's because I didn't install it globally. Using npx is just like calling the script directly `node_models/.bin/rooibosC ... `
