### ISSUE TITLE
Having trouble isntalling via npm

### ISSUE THREAD

**Issue by mcrowson** [georgejecook/rooibosPreprocessor#5]
I'm installing the preprocessor as described in the docs with npm

```bash
matthew@ubuntu-desktop:~/Downloads$ npm install -g rooibos-preprocessor
/home/matthew/.npm-packages/bin/rooibosC -> /home/matthew/.npm-packages/lib/node_modules/rooibos-preprocessor/dist/cli.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/rooibos-preprocessor/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ rooibos-preprocessor@2.1.0
added 251 packages from 128 contributors in 9.797s
matthew@ubuntu-desktop:~/Downloads$ rooibosC -h
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module './RuntimeConfig'
Require stack:
- /home/matthew/.npm-packages/lib/node_modules/rooibos-preprocessor/dist/lib/RooibosProcessor.js
- /home/matthew/.npm-packages/lib/node_modules/rooibos-preprocessor/dist/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/matthew/.npm-packages/lib/node_modules/rooibos-preprocessor/dist/lib/RooibosProcessor.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
matthew@ubuntu-desktop:~/Downloads$ which rooibosC
/home/matthew/.npm-packages/bin/rooibosC
matthew@ubuntu-desktop:~/Downloads$ node -v
v12.1.0
matthew@ubuntu-desktop:~/Downloads$ npm -v
6.9.0
```

**Comment by georgejecook** [comment]
okay - I just did a fresh install here and it worked fine.. 
do you have typescript installed globally?

**Comment by georgejecook** [comment]
Now using node v12.1.0 (npm v6.9.0)
Mac-mini:navSpike georgecook$ npm install -g rooibos-preprocessor
/Users/georgecook/.nvm/versions/node/v12.1.0/bin/rooibosC -> /Users/georgecook/.nvm/versions/node/v12.1.0/lib/node_modules/rooibos-preprocessor/dist/cli.js

> fsevents@1.2.9 install /Users/georgecook/.nvm/versions/node/v12.1.0/lib/node_modules/rooibos-preprocessor/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download
[fsevents] Success: "/Users/georgecook/.nvm/versions/node/v12.1.0/lib/node_modules/rooibos-preprocessor/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote
+ rooibos-preprocessor@2.1.0
added 319 packages from 153 contributors in 6.436s

the only thing I can think is that typescript needs to be installed globally

**Comment by mcrowson** [comment]
I have it installed globally and am getting the same error :( 

```bash
matthew@ubuntu-desktop:~$ npm list -g --depth=0
/home/matthew/.npm-packages/lib
├── rooibos-preprocessor@2.1.0
└── typescript@3.4.5
```

Do you think it has something to do with fsevents not installing? Looks to be OSX-only

**Comment by mcrowson** [comment]
Successfully installed on my MacBook. I think this has to do with my linux workstation. Will try and go to MacBook when running tests, but would love to be able to use my desktop for testing if possible.

**Comment by georgejecook** [comment]
ok - this is an important thing to resolve, for sure: I've just installed ubuntu on parallels and get the same result. I'll try debug it over the course of the week.

**Comment by georgejecook** [comment]
Unfortunately, you get further than I do - I get an error here: npm ERR! enoent ENOENT: no such file or directory, rename '/home/parallels/.nvm/versions/node/v12.1.0/lib/node_modules/.staging/rooibos-preprocessor-b8b9b014/node_modules/@babel/code-frame' -> '/home/parallels/.nvm/versions/node/v12.1.0/lib/node_modules/.staging/@babel/code-frame-f57920d3'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:

**Comment by cazacutudor** [comment]
@mcrowson 
![image](https://user-images.githubusercontent.com/16267898/57010605-3bc6d200-6c06-11e9-896c-76494da09ff6.png)

**Comment by mcrowson** [comment]
That fixed it! Looked on my Mac and it installs as RunTimeConfig.js as well.

Looking through the source all of the references to the file are just capitalizing the R and C. So Maybe OSX is just a bit more forgiving on an incorrectly capitalized filename? Maybe NPM just need to be updated?
